### ISSUE TITLE
Unable to enable SlimefunWarfare

### ISSUE THREAD

**Issue by enzof2003** [Seggan/SlimefunWarfare#18]
Hello, 
I had trouble making slimefun Warfare work on my server,
I'm on DEV 29 for SFWarfare
RC21 for Slimefun
And DEV92 for CS-Corelib

My server is 1.16.1 Paper with Java 11

Every restart, i see this in the console : 

java.lang.NoSuchFieldError: HIDE_DYE
at io.github.seggan.slimefunwarfare.items.powersuits.PowerSuit.<init>(PowerSuit.java:36) ~[?:?]
at io.github.seggan.slimefunwarfare.Setup.setupSuits(Setup.java:337) ~[?:?]
at io.github.seggan.slimefunwarfare.SlimefunWarfare.onEnable(SlimefunWarfare.java:80) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-138]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-138]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-138]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-138]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-138]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-138]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]
at java.lang.Thread.run(Thread.java:834) [?:?]

Looking forward to your answer

**Comment by Seggan** [comment]
First, remove cscorelib. It isn't needed anymore. 2nd, what server software are you using? (i.e. paper, spigot) 3rd, any way you could update to 1.16.5?

**Comment by enzof2003** [comment]
Thank for the answer :
I've removed CS corelib, nothing changed

I'm using Paper 1.16.1 138
And sadly no, i can't update to 1.16.5 due to one of the admin refusing to update.

**Comment by Seggan** [comment]
Should be fixed in next build
