### ISSUE TITLE
Need help with generating Space

### ISSUE THREAD

**Issue by CoRRupTeD-sHaDow** [Seggan/SlimefunWarfare#27]
### Discussed in https://github.com/Seggan/SlimefunWarfare/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **CoRRupTeD-sHaDow** June 18, 2021</sup>
I have a problem on my Server that i cant generate a space world.
When i Rightclick the FLOX it creates a new world that should be a world with nothing and some Ores but on my Server it generates a couple chunks without anything besides the Ores but then after some Chunks, it starts generating a normal Minecraft World. 
I have the feeling that MultiVerse is doing that Error so i wanted to ask if there is a way to generate it manually or if there is a generator that i can type in the World Creation of MultiVerse?

EDIT: After deleting the World and trying to generate another World i get this Error Message after Right clicking FLOX

> [15:15:08 ERROR]: [SlimefunWarfare] Item "FLOX" from SlimefunWarfare vDEV - 42 (git 5210dc94) has caused an Error!
[15:15:08 ERROR]: [SlimefunWarfare] You can report it here: https://github.com/Seggan/SlimefunWarfare/issues
[15:15:08 ERROR]: [SlimefunWarfare] Could not pass "ItemUseHandler" for FLOX - 'FLOX' (SlimefunWarfare vDEV - 42 (git 5210dc94))
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleportAsync(CraftPlayer.java:864) ~[patched_1.16.5.jar:git-Paper-625]
at io.github.thebusybiscuit.slimefun4.libraries.paperlib.features.asyncteleport.AsyncTeleportPaper_13.teleportAsync(AsyncTeleportPaper_13.java:13) ~[?:?]
at io.github.thebusybiscuit.slimefun4.libraries.paperlib.environments.Environment.teleport(Environment.java:101) ~[?:?]
at io.github.thebusybiscuit.slimefun4.libraries.paperlib.PaperLib.teleportAsync(PaperLib.java:76) ~[?:?]
at io.github.seggan.slimefunwarfare.items.FLOX.lambda$new$0(FLOX.java:41) ~[?:?]
at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickItem$0(SlimefunItemInteractListener.java:99) ~[?:?]
at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:928) ~[?:?]
at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickItem(SlimefunItemInteractListener.java:99) ~[?:?]
at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:67) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-625]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:494) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:485) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1752) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-625]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-625]
at java.lang.Thread.run(Thread.java:834) [?:?]</div>

**Comment by Seggan** [comment]
Can i have your full server logs?

**Comment by CoRRupTeD-sHaDow** [comment]
[latest.log](https://github.com/Seggan/SlimefunWarfare/files/6679770/latest.log)

**Comment by Seggan** [comment]
The error is because you removed the space world. Still trying to find out the reason generations isn't happening

**Comment by Seggan** [comment]
Try restarting and let the space world generate on its own

**Comment by CoRRupTeD-sHaDow** [comment]
Still getting the same Error after restarting and using Flox or is there a way to generate it without flox?

**Comment by Seggan** [comment]
It should generate a space... can I see the worlds folder?

**Comment by CoRRupTeD-sHaDow** [comment]
I dont exactly know which folder you mean so ima leave this screen here
![Screenshot_111](https://user-images.githubusercontent.com/52608863/122646391-2d5a0e00-d11f-11eb-87f8-1ac705bad7a8.png)

**Comment by CoRRupTeD-sHaDow** [comment]
even after generating a new world, it still wont generate a space world in it

**Comment by Seggan** [comment]
Thank you. That's all the info I need

**Comment by Seggan** [comment]
Space code removed in latest version
